### ISSUE TITLE
Improve completeness of minishell parsing

### ISSUE THREAD

**Issue by yenWu** [Piko-RT/pikoRT#17]
Current implementation suffers from functional correctness problems while minishell parses user's input.

* No checking postfix
```
$ lsXXX
     1 .
     1 ..
     2 dev
     3 proc
```

**Comment by mlouielu** [comment]
This is not the problem about `minishell`, is `ls.c` close the `NULL` pointer at the end.

**Comment by yenWu** [comment]
@mlouielu , probably not. It also happends on `cat`.
```
$ catcatcatcat /proc/version
Piko version 0.0.0 (uscc@uscc-Inspiron-7559) (armv7-m, cortex-m3) #Thu Aug 17 09:36:32 2017
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]
```

**Comment by mlouielu** [comment]
You can take a look via gdb, `ls dev` and `ls /dev/` isn't a parser fault, it fault inside the `ls.c`.

But your example about `cat` and `lsXXX' is a parser problem.

**Comment by yenWu** [comment]
@mlouielu , you're right. I'll tweak descriptions in this issue.
