### ISSUE TITLE
Syscall code not compatible to linux?

### ISSUE THREAD

**Issue by mlouielu** [Piko-RT/pikoRT#31]
http://elixir.free-electrons.com/linux/latest/source/arch/arm64/include/asm/unistd32.h

Current syscall list (`syscall.c`) code isn't compatible to linux.

**Comment by jserv** [comment]
Being compatible with Linux is NOT the goal of Piko/RT. Instead, PSE51 (minimal real-time system profile) should be appropriately an analog from the perspective of design.

Reference: https://www.linuxjournal.com/article/4444?page=0,1

**Comment by jserv** [comment]
I will close this issue after primitive design documents are landed though.

**Comment by mlouielu** [comment]
@jserv According to the feature matrix, PSE51 didn't contain process, does that mean the PSE51 don't need to implement `fork` or `clone` system call?

**Comment by mlouielu** [comment]
Ah, I found the description of PSE51:

```

4.3.1 Minimal Real-time System Profile IEEE Std 1003.13 PSE51

This profile is intended for embedded systems, with a single
multi-threaded process, no file system, no user and group support and
only selected options from IEEE Std 1003.1b-1993.

```

**Comment by jserv** [comment]
We do need `vfork` and `clone` system calls to validate `lmbench` on Piko/RT.

**Comment by mlouielu** [comment]
Since current `pikoRT` didn't have `process` concept, will the implement of `vfork` and `clone` be create another thread, or `process` will be implemented in `pikoRT` in the future?

**Comment by jserv** [comment]
superseded by #33
