### ISSUE TITLE
Inconsistent behavior on scheduling selection

### ISSUE THREAD

**Issue by yenWu** [Piko-RT/pikoRT#43]
`sched_select()` explicitly work as a scheduler initialization routine. It does the following tasks 1) select scheduler policy 2) initialize relative scheduler structure for specified policy. However, we expect a function to initialize the scheduler with specified policy within `start_kernel()` not just select specified policy(realized mean from the function name).

* [kernel/sched.c: sched_select()](https://github.com/Piko-RT/pikoRT/blob/master/kernel/sched.c#L9)

CC @jserv , @mlouielu .

**Comment by jserv** [comment]
Make a comprehensive list about the ways of Linux and NetBSD/FreeBSD manipulation.
