### ISSUE TITLE
Need abstraction for stm32 initialization

### ISSUE THREAD

**Issue by jserv** [Piko-RT/pikoRT#9]
The stm32-specific hardware initialization functions, `stm32f1_init` and `stm32f4_init`, are implemented in file `drivers/serial/stm32f1xx.c` and `drivers/serial/stm32f4xx.c`, that violates the abstraction of initialization flow. We should consider the way how Linux manipulates platform drivers.

**Comment by jserv** [comment]
By the way, we expect the proposed changes landed and reviewed via `refactor-stm32-hal` branch.

**Comment by yenWu** [comment]
Roger that!

**Comment by jserv** [comment]
Error: `refactor-stm32-hal` branch can not pass all test suite.

**Comment by yenWu** [comment]
@jserv , it would be passed all now. Notice that `make check` could just work on `stm32p103`.

**Comment by yenWu** [comment]
Closed: #46

**Comment by yenWu** [comment]
Closed: #46
